// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import NoticeController from "./notice_controller"
application.register("notice", NoticeController)

import SlideOverController from "./slide_over_controller"
application.register("slide-over", SlideOverController)
