---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30

:queues:
  - default

:schedule:
  ArchiveClipsJob:
    cron: '*/90 * * * *'
    queue: default
    enabled: true